services:
  # Document workflow service
  document-workflow:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - USE_FLOWABLE=true
      - FLOWABLE_URL=http://flowable:8080
    restart: unless-stopped
    depends_on:
      - flowable
    networks:
      - workflow-network

  # Flowable All-in-One
  flowable:
    image: flowable/all-in-one
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - FLOWABLE_DATABASE_TYPE=h2
      - FLOWABLE_DATABASE_UPDATE=true
      - SERVER_SERVLET_CONTEXT_PATH=/
    volumes:
      - flowable_data:/flowable-db
    networks:
      - workflow-network

networks:
  workflow-network:

volumes:
  flowable_data:
